# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-06-08 05:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('languages', models.CharField(max_length=30)),
                ('author', models.CharField(max_length=30)),
                ('pub_date', models.CharField(max_length=30)),
            ],
        ),
    ]
