# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-06-10 03:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['name']},
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='contact',
            new_name='email',
        ),
    ]
