# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-06-10 03:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_auto_20200610_0616'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='post',
            field=models.TextField(blank=True),
        ),
    ]
